### ISSUE TITLE
Noticed that not all questions are being scrapped from the site.

### ISSUE THREAD

**Issue by johnakash** [zqtay/examtopics-scraper#4]
For example the questions from https://www.examtopics.com/exams/amazon/aws-certified-solutions-architect-associate-saa-c03/ has 891 questions but when we are scrapping the questions total numbers are being reduces to 889 or so. Is that expected?

**Comment by zqtay** [comment]
This is the expected behavior.

The questions are scraped from the exam discussions [https://www.examtopics.com/discussions/](https://www.examtopics.com/discussions/), If there are no comments made to a question, it will not appear in the discussion page, means it has no way to be scraped.

You can verify this by scraping this exam:
**USGBC lead-green-associate**

- [Exam page](https://www.examtopics.com/exams/usgbc/leed-green-associate/) shows 107 questions
- [Discussions page](https://www.examtopics.com/discussions/usgbc/) shows 1 question

Only 1 question will be scraped.
